name: 'Publish MC Mods'
description: 'Publishes minecraft mods to Curseforge and Modrinth'

author: tristankechlo
branding:
  icon: 'box'
  color: 'green'

inputs:
  mc-version:
    required: true
    type: string
    description: the minecraft version of the build, used for publishing to curseforge and modrinth
  mod-version:
    required: true
    type: string
    description: the version of the mod, used for publishing to curseforge and modrinth
  curseforge-id:
    required: true
    type: number
    description: the project id for the mod
  modrinth-id:
    required: true
    type: string
    description: the project id for the mod
  changelog:
    required: true
    type: string
    default: ""
    description: changelog that is added while publishing to curseforge and modrinth, supports markdown
  loaders:
    required: false
    default: "forge,fabric,neoforge"
    type: string
    description: what loaders does this build support, used for publishing to curseforge and modrinth
  version-range:
    required: true
    type: string
    description: what minecraft versions does this build support, used for curseforge and modrinth
  version-type:
    required: false
    default: "release"
    type: string
    description: what type of version is this, used for publishing to curseforge and modrinth
  curseforge-token:
    required: true
    type: string
  modrinth-token:
    required: true
    type: string
  neoforge-glob:
    required: false
    default: "./neoforge/build/libs/*-neoforge-!(*-dev|*-sources|*-javadoc).jar"
    type: string
    description: glob pattern for the neoforge jar file
  fabric-glob:
    required: false
    default: "./fabric/build/libs/*-fabric-!(*-dev|*-sources|*-javadoc).jar"
    type: string
    description: glob pattern for the fabric jar file
  forge-glob:
    required: false
    default: "./forge/build/libs/*-forge-!(*-dev|*-sources|*-javadoc).jar"
    type: string
    description: glob pattern for the forge jar file

runs:
  using: "composite"
  steps:
    - name: determine active loaders
      id: setup
      shell: python {0}
      run: |
        import os
        loaders = [loader.strip() for loader in ${{ toJSON(inputs.loaders) }}.lower().split(",")]
        output = {loader: "yes" if loader in loaders else "no" for loader in ["forge", "fabric", "neoforge"]}
        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
          for key, value in output.items():
            print(f'{key}={value}', file=f)

    - name: publish NeoForge
      if: ${{ steps.setup.outputs.neoforge == 'yes' }}
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: ${{ inputs.modrinth-id }}
        modrinth-featured: true
        modrinth-unfeature-mode: intersection
        modrinth-token: ${{ inputs.modrinth-token }}
        modrinth-name: ${{ inputs.mc-version }} - ${{ inputs.mod-version }} - NeoForge
        modrinth-version: ${{ inputs.mc-version }}-${{ inputs.mod-version }}-NeoForge
        curseforge-id: ${{ inputs.curseforge-id }}
        curseforge-token: ${{ inputs.curseforge-token }}
        curseforge-name: ""
        curseforge-version: ""
        version-type: ${{ inputs.version-type }}
        loaders: neoforge
        files: ${{ inputs.neoforge-glob }}
        changelog: "${{ inputs.changelog }}"
        game-versions: ${{ inputs.version-range }}
        game-version-filter: ${{ inputs.version-type }}s

    - name: publish Fabric
      if: ${{ steps.setup.outputs.fabric == 'yes' }}
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: ${{ inputs.modrinth-id }}
        modrinth-featured: true
        modrinth-unfeature-mode: intersection
        modrinth-token: ${{ inputs.modrinth-token }}
        modrinth-name: ${{ inputs.mc-version }} - ${{ inputs.mod-version }} - Fabric
        modrinth-version: ${{ inputs.mc-version }}-${{ inputs.mod-version }}-Fabric
        curseforge-id: ${{ inputs.curseforge-id }}
        curseforge-token: ${{ inputs.curseforge-token }}
        curseforge-name: ""
        curseforge-version: ""
        version-type: ${{ inputs.version-type }}
        loaders: fabric
        files: ${{ inputs.fabric-glob }}
        changelog: "${{ inputs.changelog }}"
        game-versions: ${{ inputs.version-range }}
        dependencies: fabric-api(required)
        game-version-filter: ${{ inputs.version-type }}s

    - name: publish Forge
      if: ${{ steps.setup.outputs.forge == 'yes' }}
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: ${{ inputs.modrinth-id }}
        modrinth-featured: true
        modrinth-unfeature-mode: intersection
        modrinth-token: ${{ inputs.modrinth-token }}
        modrinth-name: ${{ inputs.mc-version }} - ${{ inputs.mod-version }} - Forge
        modrinth-version: ${{ inputs.mc-version }}-${{ inputs.mod-version }}-Forge
        curseforge-id: ${{ inputs.curseforge-id }}
        curseforge-token: ${{ inputs.curseforge-token }}
        curseforge-name: ""
        curseforge-version: ""
        version-type: ${{ inputs.version-type }}
        loaders: forge
        files: ${{ inputs.forge-glob }}
        changelog: "${{ inputs.changelog }}"
        game-versions: ${{ inputs.version-range }}
        game-version-filter: ${{ inputs.version-type }}s
