name: 'Publish MC Mods'
description: 'Publishes minecraft mods to Curseforge and Modrinth'

author: tristankechlo
branding:
  icon: 'box'
  color: 'green'

inputs:
# general inputs
  summary:
    required: false
    default: true
    description: when set to true this action will create a summary inside your workflow
  dryrun:
    required: false
    default: false
    description: when set to true the requests to the platform will not be executed
# minecraft specific inputs
  mod-id:
    required: true
    description: th minecraft id of your mod
  mod-version:
    required: true
    description: the version of the mod, used for publishing to curseforge and modrinth
  minecraft-version:
    required: true
    description: the minecraft version of the build, used for publishing to curseforge and modrinth
  changelog:
    required: false
    default: ""
    description: changelog that is added to the file while publishing to curseforge and modrinth
  version-range:
    required: true
    description: what minecraft versions does this build support, used for curseforge and modrinth
  version-type:
    required: false
    default: release
    description: the version type - alpha, beta, or release
# platform specific inputs
  curseforge-id:
    required: false
    default: ""
    description: the project id for the mod
  curseforge-token:
    required: false
    default: ""
    description: the token to authorize against the curseforge api
  curseforge-name:
    required: false
    default: ""
    description: the name of the version
  curseforge-version:
    required: false
    default: ""
    description: the version number
  changelog-format:
    required: true
    default: text
    description: the formatting of the changelog [text, html, markdown] (only effective on curseforge)
  modrinth-id:
    required: false
    default: ""
    description: the project id for the mod
  modrinth-token:
    required: false
    default: ""
    description: the token to authorize against the modrinth api
  modrinth-name:
    required: false
    default: ""
    description: the name of the version
  modrinth-version:
    required: false
    default: ""
    description: the version number
  featured:
    required: false
    default: false
    description: whether or not the file is marked as featured on modrinth (no used shown by modrinth?)
#loader specific inputs:
  forge-path:
    required: false
    default: ""
    description: if provided, this single file will be uploaded to curseforge and modrinth
  forge-dependencies:
    required: false
    default: ""
    description: forge specific dependencies that will be declared on curseforge and modrinth
  fabric-path:
    required: false
    default: ""
    description: if provided, this single file will be uploaded to curseforge and modrinth
  fabric-dependencies:
    required: false
    default: ""
    description: fabric specific dependencies that will be declared on curseforge and modrinth
  neoforge-path:
    required: false
    default: ""
    description: if provided, this single file will be uploaded to curseforge and modrinth
  neoforge-dependencies:
    required: false
    default: ""
    description: neoforge specific dependencies that will be declared on curseforge and modrinth

runs:
  using: "node22"
  main: ./dist/index.js
